# Generated by Django 5.1 on 2024-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField(default=0)),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_ratings', models.IntegerField(default=0)),
            ],
        ),
    ]
